Import torch

In [1]:
from torch import *

Create simple tensor

In [2]:
tensor = LongTensor([1, 2, 3, 4, 5])

print(tensor.size())
print(tensor)

torch.Size([5])
tensor([1, 2, 3, 4, 5])


Create multidimensional tensor

In [3]:
tensor = LongTensor([
    [[1, 2],
     [2, 4],
     [3, 9],
     [4, 10]]
])

# In front projection
# # -> 1d
# |   1
# 2d  2
#     3
#     4
#
# In right side projection
# # -> 3d
# |   1  2
# 2d  2  4
#     3  9
#     4  10

print(tensor)
print(tensor.size())

tensor([[[ 1,  2],
         [ 2,  4],
         [ 3,  9],
         [ 4, 10]]])
torch.Size([1, 4, 2])


view() operation "casts" tensor to target dimensions, it ignores current tensor structure

In [4]:
tensor = LongTensor([[[1, 2], [2, 4], [3, 9], [4, 10]]])

tensor = tensor.view(8) # transform to 1-d linear, where 8 - excpted size in first dim

print(tensor)
print(tensor.size())

tensor([ 1,  2,  2,  4,  3,  9,  4, 10])
torch.Size([8])


In [7]:
tensor = LongTensor([[[1, 2], [2, 4], [3, 9], [4, 10]]])

tensor = tensor.view(4, 2) # transform to 2-d linear, where 4 - excpted size in first dim, 2 - in second dim

print(tensor)
print(tensor.size())

tensor([[ 1,  2],
        [ 2,  4],
        [ 3,  9],
        [ 4, 10]])
torch.Size([4, 2])


view() also supports -1 value for dimension size, it means that the size in this dimensions will be calculated using current tensor elements count

In [9]:
tensor = LongTensor([[[1, 2], [2, 4], [3, 9], [4, 10]]])

tensor = tensor.view(4, -1) # transform to 2-d linear, where 4 - excpted size in first dim, -1 determines any size in second dim

print(tensor)
print(tensor.size())

# Other example

tensor = LongTensor([[[[2, 3, 1, 2], [8, 1, 2, 4]], [[1, 1, 3, 9], [0, 8, 4, 10]]]])

tensor = tensor.view(4, -1) # transform to 2-d linear, where 4 - excpted size in first dim, -1 determines any size in second dim

print(tensor)
print(tensor.size())

tensor([[ 1,  2],
        [ 2,  4],
        [ 3,  9],
        [ 4, 10]])
torch.Size([4, 2])
tensor([[ 2,  3,  1,  2],
        [ 8,  1,  2,  4],
        [ 1,  1,  3,  9],
        [ 0,  8,  4, 10]])
torch.Size([4, 4])


permute() operation "swaps" dimensions in tensor

In [10]:
tensor = LongTensor([[1, 2], [3, 4], [5, 6]])

print(tensor)
print(tensor.size())

# # -> 1d
# |   1  2
# 2d  3  4
#     5  6

tensor = tensor.permute((1, 0))

# # -> 1d (old 2d)
# |    
# 2d    1  3  5
# old   2  4  6
# 1d

print(tensor)
print(tensor.size())

tensor([[1, 2],
        [3, 4],
        [5, 6]])
torch.Size([3, 2])
tensor([[1, 3, 5],
        [2, 4, 6]])
torch.Size([2, 3])


In [17]:
tensor = LongTensor([[[1, 2], [3, 4], [5, 6]], [[-1, -2], [-3, -4], [-5, -6]]])

print(tensor)
print(tensor.size())

tensor = tensor.permute((1, 0, 2))

print(tensor)
print(tensor.size())

tensor([[[ 1,  2],
         [ 3,  4],
         [ 5,  6]],

        [[-1, -2],
         [-3, -4],
         [-5, -6]]])
torch.Size([2, 3, 2])
tensor([[[ 1,  2],
         [-1, -2]],

        [[ 3,  4],
         [-3, -4]],

        [[ 5,  6],
         [-5, -6]]])
torch.Size([3, 2, 2])


permute is more recommended to ... permute! tensor dimensions, but it can't be used anywhere

In [14]:
tensor = LongTensor([1, 2, 3, 4]).permute((-1, 0)) # can't create NEW dimensions

RuntimeError: permute(sparse_coo): number of dimensions in the tensor input does not match the length of the desired ordering of dimensions i.e. input.dim() = 1 is not equal to len(dims) = 2

torch.cat() concatenates the given sequence of tensors in the some dimension. All tensors must have same shape (except target dimension)

In [50]:
# Not equal size in first dim
tensor1 = Tensor([1, 2, 3, 4, 5, 6])
tensor2 = Tensor([-1, -2, -3, -4])

print(tensor1)
print(tensor1.size())
print(tensor2)
print(tensor2.size())

tensor = cat((tensor1, tensor2), 0) # linear concatenation
print(tensor)
print(tensor.size())

tensor([1., 2., 3., 4., 5., 6.])
torch.Size([6])
tensor([-1., -2., -3., -4.])
torch.Size([4])
tensor([ 1.,  2.,  3.,  4.,  5.,  6., -1., -2., -3., -4.])
torch.Size([10])


Concatenation to new dim

In [54]:
# Not equal size in first dim
tensor1 = Tensor([1, 2, 3, 4]).view(-1, 1) # Transform to pseudo 2d
tensor2 = Tensor([-1, -2, -3, -4]).view(-1, 1) # Transform to pseudo 2d

print(tensor1)
print(tensor1.size())
print(tensor2)
print(tensor2.size())

tensor = cat((tensor1, tensor2), 1) # linear concatenation

print(tensor)
print(tensor.size())

tensor([[1.],
        [2.],
        [3.],
        [4.]])
torch.Size([4, 1])
tensor([[-1.],
        [-2.],
        [-3.],
        [-4.]])
torch.Size([4, 1])
tensor([[ 1., -1.],
        [ 2., -2.],
        [ 3., -3.],
        [ 4., -4.]])
torch.Size([4, 2])


**Lifehacks show!**

Extend tensor to new dim in common case

In [56]:
tensor = Tensor([[[1], [2]], [[1], [2]], [[1], [2]]])

print(tensor.size())

tensor = tensor.view(*tensor.size(), 1)

print(tensor.size())

torch.Size([3, 2, 1])
torch.Size([3, 2, 1, 1])


========================================================================================================================================================================

***Neural Networks***

In [19]:
from torch.nn import *

**Simple linear module**
[documentation](https://pytorch.org/docs/stable/generated/torch.nn.Linear.html?highlight=linear#torch.nn.Linear)

Input: 
(∗, Hin) where ∗ means any number of dimensions including none

Output: (∗, Hout) where all but the last dimension are the same shape as the input

In [21]:
linear = Linear(5, 15)

tensor = Tensor([1, 2, 3, 4, 5])

print(tensor)
print(tensor.size())

tensor = linear(tensor)

print(tensor.size())

tensor([1., 2., 3., 4., 5.])
torch.Size([5])
torch.Size([15])


In [23]:
linear = Linear(1, 2)

tensor = Tensor([1, 2, 3, 4, 5]).view(-1, 1)

print(tensor)
print(tensor.size())

tensor = linear(tensor)

print(tensor.size())

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.]])
torch.Size([5, 1])
torch.Size([5, 2])


Linear module applies to LAST DIMENSION

**LSTM module**
[documentation](https://pytorch.org/docs/stable/generated/torch.nn.LSTM.html#torch.nn.LSTM)

num_layers – Number of recurrent layers. E.g., setting num_layers=2 would mean stacking two LSTMs together to form a stacked LSTM, with the second LSTM taking in outputs of the first LSTM and computing the final results. Default: 1

Inputs: input or pair (input, (h_0, c_0))

input: <- our input for recurrent nn module
* unbatched: (Len, Hin) 
* batched (batch_first=False): (Len, Batch, Hin)
* batched (batch_first=True): (Batch, Len, Hin)

h_0: (num_layers, Hhid) or (num_layers, Batch, Hhid) <- initial hidden state

c_0: (num_layers, Hhid) or (num_layers, Batch, Hhid) <- initial cell state

Outputs: pair (output, (h_Len, c_Len))

output:
* unbatched: (Len, Hhid) 
* batched (batch_first=False): (Len, Batch, Hhid)
* batched (batch_first=True): (Batch, Len, Hhid)

h_Len: (num_layers, Hhid) or (num_layers, Batch, Hhid) <- last hidden state

c_Len: (num_layers, Hhid) or (num_layers, Batch, Hhid) <- last cell state

In [42]:
lstm = LSTM(input_size = 1, hidden_size = 5, num_layers = 3, batch_first = False)

# seq len - 4, batch size - 2
# positive number - batch 1, negative - batch 2
tensor = Tensor([[[1], [2], [3], [4]], [[-1], [-2], [-3], [-4]]]).permute(1, 0, 2)

print(tensor)
print("main input: " + str(tensor.size()))

tensor, (h, c) = lstm(tensor)

print("main output: " + str(tensor.size()))
print("last output el: " + str(tensor[-1].size()))
print("h_Len: " + str(h.size()))
print("c_Len: " + str(c.size()))

tensor([[[ 1.],
         [-1.]],

        [[ 2.],
         [-2.]],

        [[ 3.],
         [-3.]],

        [[ 4.],
         [-4.]]])
main input: torch.Size([4, 2, 1])
main output: torch.Size([4, 2, 5])
last output el: torch.Size([2, 5])
h_Len: torch.Size([3, 2, 5])
c_Len: torch.Size([3, 2, 5])


**Embedding module** [documentation](https://pytorch.org/docs/stable/generated/torch.nn.Embedding.html#torch.nn.Embedding)

Input: (*) as LongTensor or IntTensor, every element in [0, num_embeddings)

Output: (*, embeding_dim)

In [44]:
embedding = Embedding(num_embeddings = 10, embedding_dim = 2)

tensor = LongTensor([[1, 2, 3, 4], [5, 6, 7, 8]])

print(tensor)
print(tensor.size())

tensor = embedding(tensor)

print(tensor.size())

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
torch.Size([2, 4])
torch.Size([2, 4, 2])


Embedding "extrudes" every element to new dim, extruding len equals embedding_dim